### ISSUE TITLE
bug: app always defaults to logged off state when first starting

### ISSUE THREAD

**Issue by gsong** [LeiaQuesada/MyGarden#8]
The app doesn't check if the user is in fact logged in or not upon startup. If the user is already logged in, they shouldn't be prompted to log in again.

## To Reproduce

1. Start the app
2. Log in
3. Refresh the screen

Notice the user is now in logged out state.

**Comment by gsong** [comment]
I worked through this with @sunnybrie, so you might want to consult her on how she does this in her repo, and maybe share with the rest of the cohort.

**Comment by LeiaQuesada** [comment]
Thank you for my first issue! Not sure if this was fixed as a side effect of refactoring, but unable to reproduce this issue. Please re-open if this still occurs on your end, I'll also ask other developers to inform me in their testing.
